package cli

import (
	"context"
	"flag"
	"fmt"
	"os"
	"regexp"
	"strings"
	"time"

	"github.com/compose-spec/compose-go/v2/loader"
	compose "github.com/compose-spec/compose-go/v2/types"
	"gopkg.in/yaml.v3"
)

// Output structs for clean YAML marshaling with omitempty support.

type benchOutput struct {
	Version  int                       `yaml:"version"`
	Services map[string]benchServiceOut `yaml:"services"`
}

type benchServiceOut struct {
	Dir             string            `yaml:"dir,omitempty"`
	Container       *benchContainerOut `yaml:"container,omitempty"`
	Env             map[string]string `yaml:"env,omitempty"`
	EnvFile         string            `yaml:"env_file,omitempty"`
	DependsOn       []string          `yaml:"depends_on,omitempty"`
	Restart         *benchRestartOut  `yaml:"restart,omitempty"`
	Readiness       *benchReadinessOut `yaml:"readiness,omitempty"`
	Labels          map[string]string `yaml:"labels,omitempty"`
	StopSignal      string            `yaml:"stop_signal,omitempty"`
	ShutdownTimeout string            `yaml:"shutdown_timeout,omitempty"`
}

type benchContainerOut struct {
	Image   string   `yaml:"image"`
	Ports   []string `yaml:"ports,omitempty"`
	Volumes []string `yaml:"volumes,omitempty"`
	Network string   `yaml:"network,omitempty"`
	Command []string `yaml:"command,omitempty"`
}

type benchRestartOut struct {
	Policy string `yaml:"policy"`
}

type benchReadinessOut struct {
	Kind         string `yaml:"kind"`
	URL          string `yaml:"url,omitempty"`
	Address      string `yaml:"address,omitempty"`
	Timeout      string `yaml:"timeout,omitempty"`
	InitialDelay string `yaml:"initial_delay,omitempty"`
}

func runImportCompose(args []string) int {
	fs := flag.NewFlagSet("import-compose", flag.ExitOnError)
	filePath := fs.String("file", "", "path to docker-compose.yml (required)")
	outputPath := fs.String("output", "", "output path (default: stdout)")
	_ = fs.Parse(args)

	if *filePath == "" {
		fmt.Fprintf(os.Stderr, "error: --file is required\n")
		fmt.Fprintf(os.Stderr, "usage: bench import-compose --file <docker-compose.yml> [--output <bench.yml>]\n")
		return 1
	}

	// Resolve working directory from file path
	absFile, err := absPath(*filePath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		return 1
	}
	workDir := dirName(absFile)

	// Load compose file
	ctx := context.Background()
	configDetails, err := loader.LoadConfigFiles(ctx, []string{absFile}, workDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error loading compose file: %v\n", err)
		return 1
	}

	project, err := loader.LoadWithContext(ctx, *configDetails, func(opts *loader.Options) {
		opts.SetProjectName("imported", true)
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "error parsing compose file: %v\n", err)
		return 1
	}

	// Convert to bench config
	out := convertProject(project, *filePath)

	// Marshal to YAML
	data, err := yaml.Marshal(out)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error marshaling yaml: %v\n", err)
		return 1
	}

	header := fmt.Sprintf("# Generated by: bench import-compose --file %s\n\n", *filePath)
	result := header + string(data)

	if *outputPath != "" {
		if err := os.WriteFile(*outputPath, []byte(result), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "error writing output: %v\n", err)
			return 1
		}
		fmt.Fprintf(os.Stderr, "wrote %s\n", *outputPath)
	} else {
		fmt.Print(result)
	}

	return 0
}

func convertProject(project *compose.Project, sourceFile string) benchOutput {
	out := benchOutput{
		Version:  1,
		Services: make(map[string]benchServiceOut),
	}

	for _, svc := range project.Services {
		name := svc.Name

		// Warn about build-only services
		if svc.Build != nil && svc.Image == "" {
			fmt.Fprintf(os.Stderr, "warning: service %q has build config but no image — skipping (cannot run as container without an image)\n", name)
			continue
		}
		if svc.Build != nil {
			fmt.Fprintf(os.Stderr, "warning: service %q has build config — ignoring build, using image %q\n", name, svc.Image)
		}

		benchSvc := benchServiceOut{}

		// Container config
		container := &benchContainerOut{
			Image: svc.Image,
		}

		// Ports
		for _, p := range svc.Ports {
			container.Ports = append(container.Ports, formatPort(p))
		}

		// Volumes (bind mounts only)
		for _, v := range svc.Volumes {
			if v.Type == "bind" || v.Type == "" {
				vol := v.Source + ":" + v.Target
				if v.ReadOnly {
					vol += ":ro"
				}
				container.Volumes = append(container.Volumes, vol)
			}
		}

		// Network
		if svc.NetworkMode != "" {
			container.Network = svc.NetworkMode
		}

		// Command
		if len(svc.Command) > 0 {
			container.Command = []string(svc.Command)
		}

		benchSvc.Container = container

		// Environment
		if len(svc.Environment) > 0 {
			env := make(map[string]string)
			for k, v := range svc.Environment {
				if v != nil {
					env[k] = *v
				}
			}
			if len(env) > 0 {
				benchSvc.Env = env
			}
		}

		// Env file
		if len(svc.EnvFiles) > 0 {
			benchSvc.EnvFile = svc.EnvFiles[0].Path
			if len(svc.EnvFiles) > 1 {
				fmt.Fprintf(os.Stderr, "warning: service %q has %d env_file entries — only the first is used\n", name, len(svc.EnvFiles))
			}
		}

		// Depends on
		for dep := range svc.DependsOn {
			benchSvc.DependsOn = append(benchSvc.DependsOn, dep)
		}
		sortStrings(benchSvc.DependsOn)

		// Restart policy
		policy := mapRestartPolicy(svc.Restart)
		if policy != "" && policy != "never" {
			benchSvc.Restart = &benchRestartOut{Policy: policy}
		}

		// Stop signal
		if svc.StopSignal != "" {
			benchSvc.StopSignal = svc.StopSignal
		}

		// Stop grace period → shutdown_timeout
		if svc.StopGracePeriod != nil {
			d := time.Duration(*svc.StopGracePeriod)
			if d > 0 {
				benchSvc.ShutdownTimeout = d.String()
			}
		}

		// Labels
		if len(svc.Labels) > 0 {
			benchSvc.Labels = svc.Labels
		}

		// Healthcheck → readiness
		if svc.HealthCheck != nil && !svc.HealthCheck.Disable {
			readiness := convertHealthcheck(svc.HealthCheck, name)
			if readiness != nil {
				benchSvc.Readiness = readiness
			}
		}

		// Warn about unsupported fields
		warnUnsupported(name, svc)

		out.Services[name] = benchSvc
	}

	return out
}

func formatPort(p compose.ServicePortConfig) string {
	host := p.Published
	target := fmt.Sprintf("%d", p.Target)

	if p.HostIP != "" {
		return fmt.Sprintf("%s:%s:%s", p.HostIP, host, target)
	}
	return fmt.Sprintf("%s:%s", host, target)
}

func mapRestartPolicy(policy string) string {
	// Strip retry count suffix like "on-failure:5"
	base := policy
	if idx := strings.Index(policy, ":"); idx >= 0 {
		base = policy[:idx]
	}

	switch base {
	case "no", "":
		return "never"
	case "on-failure":
		return "on-failure"
	case "always", "unless-stopped":
		return "always"
	default:
		return "never"
	}
}

var httpURLPattern = regexp.MustCompile(`(?:curl|wget)\s+.*?(https?://[^\s"']+)`)

func convertHealthcheck(hc *compose.HealthCheckConfig, svcName string) *benchReadinessOut {
	if len(hc.Test) == 0 {
		return nil
	}

	readiness := &benchReadinessOut{}

	// Set timeout and initial_delay
	if hc.Timeout != nil {
		d := time.Duration(*hc.Timeout)
		if d > 0 {
			readiness.Timeout = d.String()
		}
	}
	if hc.StartPeriod != nil {
		d := time.Duration(*hc.StartPeriod)
		if d > 0 {
			readiness.InitialDelay = d.String()
		}
	}

	// Parse the test command
	// Format is typically ["CMD", ...] or ["CMD-SHELL", "shell command"]
	var testStr string
	if len(hc.Test) >= 2 && (hc.Test[0] == "CMD-SHELL" || hc.Test[0] == "CMD") {
		testStr = strings.Join(hc.Test[1:], " ")
	} else {
		testStr = strings.Join(hc.Test, " ")
	}

	// Try to detect HTTP URL from curl/wget commands
	if matches := httpURLPattern.FindStringSubmatch(testStr); len(matches) > 1 {
		readiness.Kind = "http"
		readiness.URL = matches[1]
		return readiness
	}

	// Try to detect TCP check patterns (nc, bash /dev/tcp, etc.)
	if strings.Contains(testStr, "/dev/tcp/") || strings.Contains(testStr, "nc ") || strings.Contains(testStr, "nc -") {
		// Best-effort: try to extract host:port
		readiness.Kind = "tcp"
		addr := extractTCPAddress(testStr)
		if addr != "" {
			readiness.Address = addr
		}
		return readiness
	}

	// Cannot auto-map — warn and skip
	fmt.Fprintf(os.Stderr, "warning: service %q healthcheck could not be auto-mapped to readiness (original: %s)\n", svcName, testStr)
	return nil
}

var tcpDevPattern = regexp.MustCompile(`/dev/tcp/([^\s/]+)/(\d+)`)
var ncPattern = regexp.MustCompile(`nc\s+(?:-[^\s]+\s+)*([^\s]+)\s+(\d+)`)

func extractTCPAddress(cmd string) string {
	if matches := tcpDevPattern.FindStringSubmatch(cmd); len(matches) == 3 {
		return matches[1] + ":" + matches[2]
	}
	if matches := ncPattern.FindStringSubmatch(cmd); len(matches) == 3 {
		return matches[1] + ":" + matches[2]
	}
	return ""
}

func warnUnsupported(name string, svc compose.ServiceConfig) {
	if svc.Deploy != nil {
		fmt.Fprintf(os.Stderr, "warning: service %q has deploy config — ignored\n", name)
	}
	if len(svc.Configs) > 0 {
		fmt.Fprintf(os.Stderr, "warning: service %q has configs — ignored\n", name)
	}
	if len(svc.Secrets) > 0 {
		fmt.Fprintf(os.Stderr, "warning: service %q has secrets — ignored\n", name)
	}
}

func sortStrings(s []string) {
	for i := 0; i < len(s); i++ {
		for j := i + 1; j < len(s); j++ {
			if s[i] > s[j] {
				s[i], s[j] = s[j], s[i]
			}
		}
	}
}

// absPath returns the absolute path for a file.
func absPath(path string) (string, error) {
	if len(path) > 0 && path[0] == '/' {
		return path, nil
	}
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	return wd + "/" + path, nil
}

// dirName returns the directory part of a path.
func dirName(path string) string {
	for i := len(path) - 1; i >= 0; i-- {
		if path[i] == '/' {
			return path[:i]
		}
	}
	return "."
}
